test dockerhub

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,3 +1,4 @@
+  
 version: 2.1
 jobs:
   build:
@@ -5,11 +6,26 @@ jobs:
     - image: circleci/node
     steps:
     - checkout
+    - run: |
+        if [ -z "$NICK_TEST" ]; then
+          echo "No NICK_TEST is set! Failing..."
+          exit 1;
+        else
+          echo "Credentials are available. Let's fetch the data!"
+        fi
+        
+  deploy:
+    docker:
+    - image: circleci/node
+    steps:
+    - checkout
     - run:
         name: say hi
-        command: sleep 125
+        command: sleep 124
 workflows:
   version: 2
   build-test-and-deploy:
     jobs:
-    - build
+    - build:
+        context: everyone
+    - deploy
